routes/web.php
<?php

// use App\Events\AccessCalendar;
use App\Events\TicketBought;
use App\Http\Controllers\HomeController;
use App\Mail\Invoice;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Movies
Route::get('/', "MovieController@index");
Route::get('/movie-preview', "MovieController@preview")->name("movie.preview");
//! IDee für Previews - Ansonsten werden auch alle alten Spielzeiten angezeigt, sollte derselbe Filme auch in der nächsten Woche laufen 
Route::get('/movie-preview-show/{movie}', "MovieController@showPreview")->name("movie.showPreview");
Route::get('/movie-program', "MovieController@all")->name("movie.all");

Route::resource('/movie', "MovieController");

// Events
Route::resource('/event', "EventController");

// Tickets
Route::delete('/destroy-tickets-with-different-event', 'TicketController@destroyTicketsWithDifferentEvent')->name("ticket.destroyTicketsWithDifferentEvent");
Route::get('/bad-tickets', 'TicketController@badTickets')->name('ticket.badTickets');
Route::delete('destroy-bad-tickets', 'TicketController@destroyBadTickets')->name('ticket.destroyBadTickets');
Route::resource('/ticket', "TicketController");

// Calendar
Route::get('/calendar', 'CalendarController@index')->name("calendar.index");
Route::get('/calendar-show-with-tools', 'CalendarController@showWithTools')->name("calendar.showWithTools");
Route::get('/calendar-show-without-tools', 'CalendarController@showWithoutTools')->name("calendar.showWithoutTools");
Route::post('/calendar-fetch', 'CalendarController@fetchEvents')->name("calendar.fetchEvents");
Route::post('/calendar-check', 'CalendarController@checkIfMovieInOwnDb')->name("calendar.check");
Route::post('/calendar-insert-new-event', 'CalendarController@insertNewEvent')->name('calendar.insertNewEvent');
Route::post('/calendar-insert-new-movie-and-event', 'CalendarController@insertNewMovieAndEvent')->name('calendar.insertNewMovieAndEvent');
Route::delete('/calendar-destroy', 'CalendarController@destroy')->name("calendar.destroy");
Route::put('/calendar-update', 'CalendarController@update')->name("calendar.update");
Route::put('/calendar-release', 'CalendarController@release')->name("calendar.release");
Route::delete('/calendar-logout', 'CalendarController@logout')->name("calendar.logout");
// Calendar CURL
Route::get('/calendar-search-results', 'CalendarController@searchResults')->name("calendar.searchResults");
Route::get('/calendar-get-search-result-data', 'CalendarController@getSelectedMovieData')->name("calendar.getSearchResultData");

// PAYMENT/STRIPE
Route::post('/charge-online', 'PaymentController@chargeOnline')->name("charge.online");
Route::put('/charge-at-reception/cash', 'PaymentController@chargeAtReceptionWithCash')->name("charge.atReceptionWithCash");
Route::get('/in-payment/{reservation?}', 'PaymentController@awaitCash')->name("payment.awaitCash");
Route::put('/set-sold', 'PaymentController@manuallySetSold')->name("payment.setSold");
Route::get('/payment-success', 'PaymentController@success')->name("payment.success");
//! TODO 
Route::get('/payment-failure', 'PaymentController@failure')->name("payment.failure");

// CART
Route::get('/cart', 'CartController@index')->name("cart.index");

// Reservations
Route::put('/reserve', 'ReservationController@reserve')->name("reservation.reserve");
Route::get('/reservation-success', 'ReservationController@success')->name("reservation.success");
//! TODO 
Route::get('/reservation-failure', 'ReservationController@failure')->name("reservation.failure");

// Support
Route::put('/send-refund-mail', 'SupportController@sendMail')->name("support.sendMail");

// Users
Route::get('/user/trash', 'UserController@indexTrash')->name('user.indexTrash');
Route::put('/user/untrash/{user}', 'UserController@untrash')->name('user.untrash');
Route::delete('/user/destroytrash/{user}', 'UserController@destroyTrash')->name('user.destroyTrash');
Route::resource('/user', 'UserController');

// Employee
Route::resource('/employee', 'EmployeeController');

// Register/Login/Gates
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/home', 'HomeController');

// Search Tickets
Route::get('/search', 'SearchController@checkIfBoughtOrReservation')->name('search.find');
Route::get('/search/{code}/{type?}/{condition?}/{status?}', 'SearchController@showResults')->name("search.show");

// Legal Notice
Route::view("/agb", "legal.agb");
Route::view("/legal-notice", "legal.legal_notice");

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ticket;
use App\Traits\CartItemCount;
use App\Traits\GetEventData;
use App\Traits\GetUser;
use App\Traits\SelectTickets;
use Illuminate\Http\Request;

class SearchController extends Controller
{
    use SelectTickets, GetUser, CartItemCount, GetEventData;

    public function __construct()
    {
        $this->middleware(['auth', 'can:admin&employee']);
    }

    /**
     * Check if Ticket for given code from Request Object is reserved or bought
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function checkIfBoughtOrReservation(Request $request)
    {
        $request->validate([
            "searchCode" => "min:4|max:4",
        ]);
        // Search Boughttickets 
        $boughtTickets = $this->searchForTickets("receipt", "order_code", $request->input("searchCode"), config("constants.ticket_status_codes.bought_online"));
        if ($boughtTickets) {
            return redirect()->action("SearchController@showResults",  ["code" => $request->searchCode, "condition" => "order_code", "type" => "receipt", "status" => config("constants.ticket_status_codes.bought_online")]);
        }

        // Search Reservations
        $reservedTickets = $this->searchForTickets("reservation", "reservation_code", $request->input("searchCode"),  config("constants.ticket_status_codes.reserved"));
        if ($reservedTickets) {
            return redirect()->action("SearchController@showResults", ["code" => $request->searchCode, "condition" => "reservation_code", "type" => "reservation", "status" => config("constants.ticket_status_codes.reserved")]);
        }

        return redirect()->action("SearchController@showResults", ["code" => $request->searchCode]);
    }

    /**
     * Show Searchresults for given code
     * @param string $code order- or reservationcode
     * @param string|null $ticketType
     * @param string|null $condition DB query condition
     * @param int|null $value ticket Statuscode
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function showResults($code, $ticketType = null, $condition = null, $value = null)
    {
        $user = $this->getUser();
        $cartQuantity = $this->cartItemCount($user);

        $total = 0;
        $tickets = collect([]);
        if ($ticketType) {
            $tickets = Ticket::whereHas($ticketType, function ($query) use ($condition, $code) {
                $query->where($condition, $code);
            })->get();
            if ($tickets->count()) {
                $total = $tickets->sum("price");
                $eventData = $this->getEventData($tickets[0]->event);
                return view("search.results", compact("user", "ticketType", "code", "eventData", "tickets", "total", "ticketType"));
            }
        }
        return view("search.results", compact("code", "tickets", "total", "ticketType", "cartQuantity"));
    }

    /**
     * Search for Tickets 
     * @param string $condition1 DB query condition
     * @param string $condition2 DB query condition
     * @param string $condition3 DB query condition
     * @param int $value Ticket Statuscode
     * @return mixed
     */
    public function searchForTickets($condition1, $condition2, $condition3, $value)
    {
        return Ticket::whereHas($condition1, function ($query) use ($condition2, $condition3) {
            $query->where($condition2, $condition3);
        })->where("status", $value)->first();
    }
}

resources/views/search/results.blade.php
@extends('layouts.app')

@section('pageTitle','Suchergebnisse')

@section('content')

@push("scripts")
<script src="{{ asset('js/tickets/deleteTicketFromSearchResult.js')}}"></script>
@endpush
<div class="container">

   <table class="table table-bordered table-responsive-sm text-center">
      @if(!$tickets->count())
      <h1 class="text-center my-4">Es wurden keine Tickets für '{{$code}}' gefunden</h1>
      @else
      <h1 class="results-header my-4 text-center">@if($ticketType == "reservation") Reservierte @else Gekaufte @endif
         Tickets für '{{$code}}'</h1>
      @endif
      <thead class="thead-inverse">
         <tr>
            <th>Film</th>
            <th>Spielzeit</th>
            <th>Saal</th>
            <th>Reihe</th>
            <th>Sitzplatz</th>
            <th>Preis</th>
            @if($ticketType == "reservation")
            <th>Entfernen</th>
            @endif
         </tr>
      </thead>
      <tbody class="search">
         @foreach ($tickets as $ticket)
         <tr>
            <td scope="row">{{$eventData["movieTitle"]}}</td>
            <td>{{ \Carbon\Carbon::parse($eventData["startEvent"])->format('H:i | d.m.Y')}}</td>
            <td>{{$eventData["roomName"]}}</td>
            <td>{{$ticket->row}}</td>
            <td>{{$ticket->seat}}</td>
            <td>{{$ticket->price}}€</td>
            @if($ticketType == "reservation")
            <td>
               <form class="formDelete search-overview" action="{{route("ticket.destroy",$ticket->id)}}" method="POST">
                  @csrf
                  @method("delete")
                  <input type="hidden" name="reservation_search_results" value="reservation_search_results">
                  <input type="hidden" name="code" value="{{$code}}">
                  <button class="btn btn-danger">
                     <svg width="1em" height="1em" viewBox="0 0 16 16" class="remove bi bi-x" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                           d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
                     </svg>
                  </button>
               </form>
            </td>
            @endif
         </tr>
         @endforeach
      </tbody>
      <tfoot class="bg-dark text-light">
         <tr>
            <td>Total:</td>
            <td class="border-0"></td>
            <td class="border-0"></td>
            <td class="border-0"></td>
            <td class="border-0"></td>
            <td><span id="total">@if(isset($total)) {{$total}}@else 0 @endif</span>€</td>
            @if($ticketType == "reservation")
            <td class="border-0"></td>
            @endif
         </tr>
      </tfoot>
   </table>

   @if($tickets->count() && $ticketType == "reservation")
   <div class="employee-charging-methods d-flex justify-content-center">
      <form class="sell-cash form" action="{{route("charge.atReceptionWithCash")}}" method="POST">
         @csrf
         @method("put")
         <input type="hidden" name="reservation_search_results" value="reservation_search_results">
         <input type="hidden" name="reservation_code" value="{{$code}}">
         <button class=" btn btn-success mr-2">Barzahlung</button>
      </form>
      <a href="endpoint" class="btn btn-success">Bankomatkarte</a>
   </div>
   @endif

   <div class="text-center my-2">
      <a href="{{route("movie.index")}}" class="redirect-home btn btn-primary">Zurück zur Filmübersicht</a>
   </div>
</div>

@endsection