routes/web.php
<?php

// use App\Events\AccessCalendar;
use App\Events\TicketBought;
use App\Http\Controllers\HomeController;
use App\Mail\Invoice;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Movies
Route::get('/', "MovieController@index");
Route::get('/movie-preview', "MovieController@preview")->name("movie.preview");
//! IDee für Previews - Ansonsten werden auch alle alten Spielzeiten angezeigt, sollte derselbe Filme auch in der nächsten Woche laufen 
Route::get('/movie-preview-show/{movie}', "MovieController@showPreview")->name("movie.showPreview");
Route::get('/movie-program', "MovieController@all")->name("movie.all");

Route::resource('/movie', "MovieController");

// Events
Route::resource('/event', "EventController");

// Tickets
Route::delete('/destroy-tickets-with-different-event', 'TicketController@destroyTicketsWithDifferentEvent')->name("ticket.destroyTicketsWithDifferentEvent");
Route::get('/bad-tickets', 'TicketController@badTickets')->name('ticket.badTickets');
Route::delete('destroy-bad-tickets', 'TicketController@destroyBadTickets')->name('ticket.destroyBadTickets');
Route::resource('/ticket', "TicketController");

// Calendar
Route::get('/calendar', 'CalendarController@index')->name("calendar.index");
Route::get('/calendar-show-with-tools', 'CalendarController@showWithTools')->name("calendar.showWithTools");
Route::get('/calendar-show-without-tools', 'CalendarController@showWithoutTools')->name("calendar.showWithoutTools");
Route::post('/calendar-fetch', 'CalendarController@fetchEvents')->name("calendar.fetchEvents");
Route::post('/calendar-check', 'CalendarController@checkIfMovieInOwnDb')->name("calendar.check");
Route::post('/calendar-insert-new-event', 'CalendarController@insertNewEvent')->name('calendar.insertNewEvent');
Route::post('/calendar-insert-new-movie-and-event', 'CalendarController@insertNewMovieAndEvent')->name('calendar.insertNewMovieAndEvent');
Route::delete('/calendar-destroy', 'CalendarController@destroy')->name("calendar.destroy");
Route::put('/calendar-update', 'CalendarController@update')->name("calendar.update");
Route::put('/calendar-release', 'CalendarController@release')->name("calendar.release");
Route::delete('/calendar-logout', 'CalendarController@logout')->name("calendar.logout");
// Calendar CURL
Route::get('/calendar-search-results', 'CalendarController@searchResults')->name("calendar.searchResults");
Route::get('/calendar-get-search-result-data', 'CalendarController@getSelectedMovieData')->name("calendar.getSearchResultData");

// PAYMENT/STRIPE
Route::post('/charge-online', 'PaymentController@chargeOnline')->name("charge.online");
Route::put('/charge-at-reception/cash', 'PaymentController@chargeAtReceptionWithCash')->name("charge.atReceptionWithCash");
Route::get('/in-payment/{reservation?}', 'PaymentController@awaitCash')->name("payment.awaitCash");
Route::put('/set-sold', 'PaymentController@manuallySetSold')->name("payment.setSold");
Route::get('/payment-success', 'PaymentController@success')->name("payment.success");
//! TODO 
Route::get('/payment-failure', 'PaymentController@failure')->name("payment.failure");

// CART
Route::get('/cart', 'CartController@index')->name("cart.index");

// Reservations
Route::put('/reserve', 'ReservationController@reserve')->name("reservation.reserve");
Route::get('/reservation-success', 'ReservationController@success')->name("reservation.success");
//! TODO 
Route::get('/reservation-failure', 'ReservationController@failure')->name("reservation.failure");

// Support
Route::put('/send-refund-mail', 'SupportController@sendMail')->name("support.sendMail");

// Users
Route::get('/user/trash', 'UserController@indexTrash')->name('user.indexTrash');
Route::put('/user/untrash/{user}', 'UserController@untrash')->name('user.untrash');
Route::delete('/user/destroytrash/{user}', 'UserController@destroyTrash')->name('user.destroyTrash');
Route::resource('/user', 'UserController');

// Employee
Route::resource('/employee', 'EmployeeController');

// Register/Login/Gates
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/home', 'HomeController');

// Search Tickets
Route::get('/search', 'SearchController@checkIfBoughtOrReservation')->name('search.find');
Route::get('/search/{code}/{type?}/{condition?}/{status?}', 'SearchController@showResults')->name("search.show");

// Legal Notice
Route::view("/agb", "legal.agb");
Route::view("/legal-notice", "legal.legal_notice");

app/Models/Movie.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    use HasFactory;

    protected $fillable = ["title", "duration", "genre", "cast", "overview", "poster_path", "release_year"];

    /**
     * Get related Eventmodel Data
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function events()
    {
        return $this->hasMany(\App\Models\Event::class);
    }

    /**
     * Get related Eventmodel Data that start in the future
     * @return mixed
     */
    public function futureEvents()
    {
        return $this->events()->withCount("tickets")->where([["start_event", ">", Carbon::now()], ["released", "=", config("constants.calendar_status_codes.released")]]);
    }

    /**
     * Get related Eventmodel Data whose end is in the future
     * @return mixed
     */
    public function futureEndEvents()
    {
        return $this->events()->withCount("tickets")->where([["end_event", ">", Carbon::now()], ["released", "=", config("constants.calendar_status_codes.released")]]);
    }

    /**
     * Get movies(/events) that are playing current week
     * @return mixed 
     */
    public function currentWeek()
    {
        return $this->events()->withCount("tickets")->whereRaw("YEARWEEK(start_event,1) = YEARWEEK(NOW(),1)")->orderBy("start_event", "asc");
    }

    /**
     * Get movies(/events) that are playing the following week
     * @return mixed 
     */
    public function nextWeek()
    {
        return $this->events()->withCount("tickets")->whereRaw("YEARWEEK(start_event,1) = YEARWEEK(NOW(),1)+1")->orderBy("start_event", "asc");
    }

    /**
     * Get movies(/events) that are playing today
     * @return mixed 
     */
    public function today()
    {
        return $this->events()->withCount("tickets")->whereRaw("DATE(start_event) = DATE(NOW())")->orderBy("start_event", "asc");
    }
}

app/Http/Controllers/MovieController.php
<?php

namespace App\Http\Controllers;

use App\Models\Movie;
use App\Traits\CartItemCount;
use App\Traits\GetUser;
use Illuminate\Http\Request;
use Carbon\Carbon;

class MovieController extends Controller
{

    use GetUser, CartItemCount;
    /**
     * Display all movies playing today
     *
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function index()
    {
        $movies = Movie::whereHas("today")->get();
        $cartQuantity = $this->cartItemCount();

        return view("movie.today", compact("movies", "cartQuantity"));
    }

    /**
     * Display all movies playing next week
     *
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function preview()
    {
        $movies = Movie::whereHas("nextWeek")->get();
        $cartQuantity = $this->cartItemCount();

        return view("movie.preview", compact("movies", "cartQuantity"));
    }

    /**
     * Display all movies playing this week
     *
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function all(Request $request)
    {

        $cartQuantity = $this->cartItemCount();

        //! OHNE AJAX
        $movies = Movie::whereHas("currentWeek")->get();
        return view("movie.all", compact("movies", "cartQuantity"));


        //! AJAX TEST
        // $movies = Movie::whereHas("currentWeek")->paginate(1);
        // if ($request->ajax()) {
        //     return $movies;
        // }
        // return view("movie.all_ajax", compact("cartQuantity"));
    }



    /**
     * Display movie with given id
     *
     * @param int $id movieId
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function show($id)
    {
        setlocale(LC_TIME, 'German');

        $cartQuantity = $this->cartItemCount();

        $movieData = Movie::with("currentWeek.room", "currentWeek.room.maxSeats")->findOrFail($id);

        $title = $movieData->title;
        $allPlaytimesPerDay = [];
        foreach ($movieData->currentWeek as $playtime) {
            $startDatetime = Carbon::parse($playtime->start_event);
            $startDate = strftime("%a", strtotime($startDatetime));
            $startDate .= $startDatetime->format(" d.m.Y");
            $endDatetime = Carbon::parse($playtime->end_event);
            $movieIsRunning = Carbon::now() > $startDatetime && Carbon::now() < $endDatetime ? true : false;
            $movieHasEnded = Carbon::now() > $endDatetime ? true : false;
            $allPlaytimesPerDay[$startDate][] = ["id" => $playtime->id, "startEvent" => $startDatetime->format("H:i"), "endEvent" => $endDatetime->format("H:i"), "roomName" => $playtime->room->name, "movieIsRunning" => $movieIsRunning, "movieHasEnded" => $movieHasEnded];
        };

        return view("movie.show", compact("title", "movieData", "allPlaytimesPerDay", "cartQuantity"));
    }

    //! TODO NEU 
    public function showPreview($id)
    {
        setlocale(LC_TIME, 'German');

        $cartQuantity = $this->cartItemCount();
        $movieData = Movie::whereHas("nextWeek")->with("nextWeek.room", "nextWeek.room.maxSeats")->findOrFail($id);

        $title = $movieData->title;
        $allPlaytimesPerDay = [];
        foreach ($movieData->nextWeek as $playtime) {
            $startDatetime = Carbon::parse($playtime->start_event);
            $startDate = strftime("%a", strtotime($startDatetime));
            $startDate .= $startDatetime->format(" d.m.Y");
            $endDatetime = Carbon::parse($playtime->end_event);
            $allPlaytimesPerDay[$startDate][] = ["id" => $playtime->id, "startEvent" => $startDatetime->format("H:i"), "endEvent" => $endDatetime->format("H:i"), "roomName" => $playtime->room->name];
        };

        return view("movie.show_preview", compact("title", "movieData", "allPlaytimesPerDay", "cartQuantity"));
    }
}

resources/views/movie/all.blade.php
@extends('layouts.app')

@section('pageTitle','Programm')

@section('content')
<div>
   <h1 class="text-center pt-4">Diese Woche im Kino</h1>
</div>

<div class="movies container d-flex justify-content-center flex-wrap">
   @foreach($movies as $movie)
   <div class="col-12 row p-5">
      <div class="col-sm-4 col-md-3">
         <a href="{{route("movie.show",$movie->id)}}">
            <img src="https://image.tmdb.org/t/p/original/{{$movie->poster_path}}" class="img-fluid" alt="">
         </a>
      </div>
      <div class="col-sm col-md-9">
         <div class="col-sm col-md-9">
            <h2 class="text-break">{{$movie->title}}</h2>
            <div class="col">
               <div class="d-none d-lg-block">
                  <div class="movie-duration row flex-nowrap">
                     <p class="col-md-5 col-lg-4"><strong>Dauer:</strong></p>
                     <p>{{$movie->duration}} Minuten</p>
                  </div>
                  <div class="movie-genre row flex-nowrap">
                     <p class="col-md-5 col-lg-4"><strong>Genre:</strong></p>
                     <p>{{$movie->genre}}</p>
                  </div>
                  <div class="movie-release-year row flex-nowrap">
                     <p class="col-md-5 col-lg-4"><strong>Veröffentlicht:</strong></p>
                     <p>{{$movie->release_year}}</p>
                  </div>
               </div>
            </div>
            <div class="col d-none d-md-block">
               <p>{{substrWords($movie->overview,100)}}</p>
               <a class="btn border border-dark btn-light" href="{{route("movie.show",$movie->id)}}">Mehr lesen</a>
            </div>
            <div class="col d-md-none">
               <p>{{substrWords($movie->overview,50)}}</p>
               <a class="btn border border-dark btn-light" href="{{route("movie.show",$movie->id)}}">Mehr lesen</a>
            </div>
         </div>
      </div>
   </div>
   @endforeach
</div>

@endsection

resources/views/movie/all_ajax.blade.php
@extends('layouts.app')

@section('pageTitle','Programm')

@section('content')
<div>
   <h1 class="text-center pt-4">Diese Woche im Kino</h1>
</div>

<div class="movies container d-flex justify-content-center flex-wrap">
</div>

<script>
   const url = "{{route("movie.all")}}";
   var newData = true;
   var fetchingData = false;
   var page = 1;
   loadContent(page);

   $(window).scroll(()=>{
      if($(window).scrollTop() + $(window).height() >= $(document).height() -20){
         if(newData && !fetchingData){
               page++;
               loadContent(page);
         }
      } 
   });

   function loadContent(page){
      fetchingData = !fetchingData;
      $('.overlay').show();
      $.ajax({
         url: url + "?page=" + page,
         type: "get",
         datatype: "html",
         success:(pageData)=>{
            const movies = pageData.data;
            $('.overlay').hide();

            if(!movies.length) {
                  newData = false;
                  return;
                  }

            let moviesMap = movies.map((movie) => {
               let route = '{{route('movie.show',':movie.id')}}'
               console.log("MOVIE ID",movie.id);
               route = route.replace(':movie.id',movie.id);
               return `<div class='col-12 row p-5'>
                     <div class='col-sm-4 col-md-3'>
                           <a href=${route}>
                              <img src='https://image.tmdb.org/t/p/original/${movie.poster_path}' class='img-fluid' alt=''>
                           </a>
                     </div>
                     <div class='col-sm col-md-9'>
                           <div class='col-sm col-md-9'>
                              <h2>${movie.title}</h2>
                              <div class='col'>
                              <div class='d-none d-lg-block'>
                                 <div class='movie-duration row flex-nowrap'>
                                       <p class='col-md-5 col-lg-4'><strong>Dauer:</strong></p>
                                       <p>${movie.duration} Minuten</p>
                                 </div>
                              </div>
                              </div>
                              <div class='col d-none d-md-block'>
                              <p>substrWords(movie.overview,100)</p>
                              <a class='btn border border-dark btn-light' href=${route}>Mehr lesen</a>
                              </div>
                           </div>
                     </div>
                  </div>`
               }).join("");

            $(".movies").append(moviesMap);
            fetchingData = !fetchingData;

         if($(window).height() == $(document).height()){
               page++;
               loadContent(page);
         }
         },
         failure:(err) => console.log(err),
      })
   };


</script>

@endsection

resources/views/movie/preview.blade.php
@extends('layouts.app')

@section('pageTitle','Vorschau')

@section('content')

<div>
   <h1 class="text-center pt-4">Vorschau</h1>
</div>
<div class="movies container d-flex justify-content-center flex-wrap">
   @foreach($movies as $movie)
   <div class="col-12 row p-5">
      <div class="col-sm-4 col-md-3">
         <a href="{{route("movie.showPreview",$movie->id)}}">
            <img src="https://image.tmdb.org/t/p/original/{{$movie->poster_path}}" class="img-fluid" alt="">
         </a>
      </div>
      <div class="col-sm col-md-9">
         <div class="col-sm col-md-9">
            <h2 class="text-break">{{$movie->title}}</h2>
            <div class="col">
               <div class="d-none d-lg-block">
                  <div class="movie-duration row flex-nowrap">
                     <p class="col-md-5 col-lg-4"><strong>Dauer:</strong></p>
                     <p>{{$movie->duration}} Minuten</p>
                  </div>
                  <div class="movie-genre row flex-nowrap">
                     <p class="col-md-5 col-lg-4"><strong>Genre:</strong></p>
                     <p>{{$movie->genre}}</p>
                  </div>
                  <div class="movie-release-year row flex-nowrap">
                     <p class="col-md-5 col-lg-4"><strong>Veröffentlicht:</strong></p>
                     <p>{{$movie->release_year}}</p>
                  </div>
               </div>
            </div>
            <div class="col d-none d-md-block">
               <p>{{substrWords($movie->overview,100)}}</p>
               <a class="btn border border-dark btn-light" href="{{route("movie.showPreview",$movie->id)}}">Mehr
                  lesen</a>
            </div>
            <div class="col d-md-none">
               <p>{{substrWords($movie->overview,50)}}</p>
               <a class="btn border border-dark btn-light" href="{{route("movie.showPreview",$movie->id)}}">Mehr
                  lesen</a>
            </div>
         </div>
      </div>
   </div>
   @endforeach
</div>

@endsection

resources/views/movie/show.blade.php
@extends('layouts.app')

@section('pageTitle','Filmdetails')

@section('content')

<div class="movie container">
   <h1 class="col-md-12 text-center p-4">{{$title}}</h1>
   <div class="row">
      <div class="img-container col-sm-4">
         <img src="https://image.tmdb.org/t/p/original/{{$movieData->poster_path}}" class="img-fluid" alt="">
      </div>
      <div class="movie-info-container col-sm-8 mt-3">
         <div class="movie-duration row">
            <p class="col-sm-6 col-md-5 col-lg-4"><strong>Dauer:</strong></p>
            <p class="col">{{$movieData->duration}} Minuten</p>
         </div>
         <div class="movie-genre row">
            <p class="col-sm-6 col-md-5 col-lg-4"><strong>Genre:</strong></p>
            <p class="col">{{$movieData->genre}}</p>
         </div>
         <div class="movie-cast row">
            <p class="col-sm-6 col-md-5 col-lg-4"><strong>Cast:</strong></p>
            <p class="col">{{$movieData->cast}}</p>
         </div>
         <div class="movie-release-year row">
            <p class="col-sm-6 col-md-5 col-lg-4"><strong>Veröffentlicht:</strong></p>
            <p class="col">{{$movieData->release_year}}</p>
         </div>
      </div>
   </div>
   <div class="movie-overview col-sm-10 my-4 ">
      <h2>Handlung</h2>
      <p>{{$movieData->overview}}</p>
      <h2 class="playtimes">
         Spielzeiten
      </h2>
      {{-- Meine "Collection" mit den Spieltagen --}}
      @foreach($allPlaytimesPerDay as $day => $playtimesPerDay)
      <div class="row p-2">
         <p class="col-sm-4 col-lg-3">{{$day}}</p>
         {{-- Die Spielzeiten für einen Spieltag --}}
         <div class="row col">
            @foreach($playtimesPerDay as $playtimePerDay)
            @if($playtimePerDay["movieHasEnded"])
            <span class="col-12 col-sm-2 text-danger">
               <p>{{$playtimePerDay["roomName"]}}</p>
               <p>{{$playtimePerDay["startEvent"]}} - {{$playtimePerDay["endEvent"]}}</p>
            </span>
            @else
            <a href="{{route("event.show",$playtimePerDay["id"])}}" class="col-12 col-sm-5">
               <p>
                  {{$playtimePerDay["roomName"]}}
               </p>
               <p>
                  {{$playtimePerDay["startEvent"]}} - {{$playtimePerDay["endEvent"]}}
               </p>
               @if($playtimePerDay["movieIsRunning"])
               <p class="text-warning movie-is-running">
                  Läuft
               </p>
               @endif
            </a>
            @endif
            @endforeach
         </div>
      </div>
      @endforeach
   </div>

</div>

<style>
   @keyframes fadeIn {
      from {
         opacity: .2;
      }
   }

   .movie-is-running {
      animation: fadeIn .7s infinite alternate;
   }
</style>
@endsection

resources/views/movie/show_preview.blade.php
@extends('layouts.app')

@section('pageTitle','Filmdetails')

@section('content')

<div class="movie container">
   <h1 class="col-md-12 text-center p-4">{{$title}}</h1>
   <div class="row">
      <div class="img-container col-sm-4">
         <img src="https://image.tmdb.org/t/p/original/{{$movieData->poster_path}}" class="img-fluid" alt="">
      </div>
      <div class="movie-info-container col-sm-8 mt-3">
         <div class="movie-duration row">
            <p class="col-sm-6 col-md-5 col-lg-4"><strong>Dauer:</strong></p>
            <p class="col">{{$movieData->duration}} Minuten</p>
         </div>
         <div class="movie-genre row">
            <p class="col-sm-6 col-md-5 col-lg-4"><strong>Genre:</strong></p>
            <p class="col">{{$movieData->genre}}</p>
         </div>
         <div class="movie-cast row">
            <p class="col-sm-6 col-md-5 col-lg-4"><strong>Cast:</strong></p>
            <p class="col">{{$movieData->cast}}</p>
         </div>
         <div class="movie-release-year row">
            <p class="col-sm-6 col-md-5 col-lg-4"><strong>Veröffentlicht:</strong></p>
            <p class="col">{{$movieData->release_year}}</p>
         </div>
      </div>
   </div>
   <div class="movie-overview col-sm-10 my-4">
      <h2>Handlung</h2>
      <p>{{$movieData->overview}}</p>
      <h2 class="playtimes">
         Spielzeiten
      </h2>
      {{-- Meine "Collection" mit den Spieltagen --}}
      @foreach($allPlaytimesPerDay as $day => $playtimesPerDay)
      <div class="row p-2">
         <p class="col-sm-4 col-lg-3">{{$day}}</p>
         {{-- Die Spielzeiten für einen Spieltag --}}
         <div class="row col">
            @foreach($playtimesPerDay as $playtimePerDay)
            <a href="{{route("event.show",$playtimePerDay["id"])}}" class="col-12 col-sm-5">
               <p>
                  {{$playtimePerDay["roomName"]}}
               </p>
               <p>
                  {{$playtimePerDay["startEvent"]}} - {{$playtimePerDay["endEvent"]}}
               </p>
            </a>
            @endforeach
         </div>
      </div>
      @endforeach
   </div>

</div>

<style>
   @keyframes fadeIn {
      from {
         opacity: .2;
      }
   }

   .movie-is-running {
      animation: fadeIn .7s infinite alternate;
   }
</style>
@endsection

resources/views/movie/today.blade.php
@extends('layouts.app')

@section('pageTitle','Alle Filme')

@section('content')

<div>
   <h1 class="text-center pt-4">Heute im Kino</h1>
</div>
<div class="movies container d-flex justify-content-center flex-wrap">
   @foreach($movies as $movie)
   <div class="col-12 row p-5">
      <div class="col-sm-4 col-md-3">
         <a href="{{route("movie.show",$movie->id)}}">
            <img src="https://image.tmdb.org/t/p/original/{{$movie->poster_path}}" class="img-fluid" alt="">
         </a>
      </div>
      <div class="col-sm col-md-9">
         <div class="col-sm col-md-9">
            <h2 class="text-break">{{$movie->title}}</h2>
            <div class="col">
               <div class="d-none d-lg-block">
                  <div class="movie-duration row flex-nowrap">
                     <p class="col-md-5 col-lg-4"><strong>Dauer:</strong></p>
                     <p>{{$movie->duration}} Minuten</p>
                  </div>
                  <div class="movie-genre row flex-nowrap">
                     <p class="col-md-5 col-lg-4"><strong>Genre:</strong></p>
                     <p>{{$movie->genre}}</p>
                  </div>
                  <div class="movie-release-year row flex-nowrap">
                     <p class="col-md-5 col-lg-4"><strong>Veröffentlicht:</strong></p>
                     <p>{{$movie->release_year}}</p>
                  </div>
               </div>
            </div>
            <div class="col d-none d-md-block">
               <p>{{substrWords($movie->overview,100)}}</p>
               <a class="btn border border-dark btn-light" href="{{route("movie.show",$movie->id)}}">Mehr lesen</a>
            </div>
            <div class="col d-md-none">
               <p>{{substrWords($movie->overview,50)}}</p>
               <a class="btn border border-dark btn-light" href="{{route("movie.show",$movie->id)}}">Mehr lesen</a>
            </div>
         </div>
      </div>
   </div>
   @endforeach
</div>

@endsection