routes/web.php
<?php

// use App\Events\AccessCalendar;
use App\Events\TicketBought;
use App\Http\Controllers\HomeController;
use App\Mail\Invoice;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Movies
Route::get('/', "MovieController@index");
Route::get('/movie-preview', "MovieController@preview")->name("movie.preview");
//! IDee für Previews - Ansonsten werden auch alle alten Spielzeiten angezeigt, sollte derselbe Filme auch in der nächsten Woche laufen 
Route::get('/movie-preview-show/{movie}', "MovieController@showPreview")->name("movie.showPreview");
Route::get('/movie-program', "MovieController@all")->name("movie.all");

Route::resource('/movie', "MovieController");

// Events
Route::resource('/event', "EventController");

// Tickets
Route::delete('/destroy-tickets-with-different-event', 'TicketController@destroyTicketsWithDifferentEvent')->name("ticket.destroyTicketsWithDifferentEvent");
Route::get('/bad-tickets', 'TicketController@badTickets')->name('ticket.badTickets');
Route::delete('destroy-bad-tickets', 'TicketController@destroyBadTickets')->name('ticket.destroyBadTickets');
Route::resource('/ticket', "TicketController");

// Calendar
Route::get('/calendar', 'CalendarController@index')->name("calendar.index");
Route::get('/calendar-show-with-tools', 'CalendarController@showWithTools')->name("calendar.showWithTools");
Route::get('/calendar-show-without-tools', 'CalendarController@showWithoutTools')->name("calendar.showWithoutTools");
Route::post('/calendar-fetch', 'CalendarController@fetchEvents')->name("calendar.fetchEvents");
Route::post('/calendar-check', 'CalendarController@checkIfMovieInOwnDb')->name("calendar.check");
Route::post('/calendar-insert-new-event', 'CalendarController@insertNewEvent')->name('calendar.insertNewEvent');
Route::post('/calendar-insert-new-movie-and-event', 'CalendarController@insertNewMovieAndEvent')->name('calendar.insertNewMovieAndEvent');
Route::delete('/calendar-destroy', 'CalendarController@destroy')->name("calendar.destroy");
Route::put('/calendar-update', 'CalendarController@update')->name("calendar.update");
Route::put('/calendar-release', 'CalendarController@release')->name("calendar.release");
Route::delete('/calendar-logout', 'CalendarController@logout')->name("calendar.logout");
// Calendar CURL
Route::get('/calendar-search-results', 'CalendarController@searchResults')->name("calendar.searchResults");
Route::get('/calendar-get-search-result-data', 'CalendarController@getSelectedMovieData')->name("calendar.getSearchResultData");

// PAYMENT/STRIPE
Route::post('/charge-online', 'PaymentController@chargeOnline')->name("charge.online");
Route::put('/charge-at-reception/cash', 'PaymentController@chargeAtReceptionWithCash')->name("charge.atReceptionWithCash");
Route::get('/in-payment/{reservation?}', 'PaymentController@awaitCash')->name("payment.awaitCash");
Route::put('/set-sold', 'PaymentController@manuallySetSold')->name("payment.setSold");
Route::get('/payment-success', 'PaymentController@success')->name("payment.success");
//! TODO 
Route::get('/payment-failure', 'PaymentController@failure')->name("payment.failure");

// CART
Route::get('/cart', 'CartController@index')->name("cart.index");

// Reservations
Route::put('/reserve', 'ReservationController@reserve')->name("reservation.reserve");
Route::get('/reservation-success', 'ReservationController@success')->name("reservation.success");
//! TODO 
Route::get('/reservation-failure', 'ReservationController@failure')->name("reservation.failure");

// Support
Route::put('/send-refund-mail', 'SupportController@sendMail')->name("support.sendMail");

// Users
Route::get('/user/trash', 'UserController@indexTrash')->name('user.indexTrash');
Route::put('/user/untrash/{user}', 'UserController@untrash')->name('user.untrash');
Route::delete('/user/destroytrash/{user}', 'UserController@destroyTrash')->name('user.destroyTrash');
Route::resource('/user', 'UserController');

// Employee
Route::resource('/employee', 'EmployeeController');

// Register/Login/Gates
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/home', 'HomeController');

// Search Tickets
Route::get('/search', 'SearchController@checkIfBoughtOrReservation')->name('search.find');
Route::get('/search/{code}/{type?}/{condition?}/{status?}', 'SearchController@showResults')->name("search.show");

// Legal Notice
Route::view("/agb", "legal.agb");
Route::view("/legal-notice", "legal.legal_notice");

app/Models/Event.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    use HasFactory;

    protected $fillable = ["movie_id", "room_id", "start_event", "end_event", "released"];

    /**
     * Get related Moviemodel Data
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function movie()
    {
        return $this->belongsTo(\App\Models\Movie::class);
    }

    /**
     * Get related Roommodel Data
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function room()
    {
        return $this->belongsTo(\App\Models\Room::class, "room_id", "id");
    }

    /**
     * Get related Ticketmodel Data
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function tickets()
    {
        return $this->hasMany(\App\Models\Ticket::class, "event_id", "id");
    }

    /**
     * Check if Reservations are still allowed for Event
     * @return mixed
     */
    public function allowReservation()
    {
        return $this->hasMany(\App\Models\Ticket::class, "event_id", "id")->where([["start_event", ">", Carbon::now()->addMinutes(30)]]);
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Models\Event;
use App\Traits\CartItemCount;
use App\Traits\GetUser;
use Carbon\Carbon;

class EventController extends Controller
{

    use GetUser, CartItemCount;

    public function __construct()
    {
        $this->middleware("prevent-history");
    }

    /**
     * Display all playtimes for movie
     *
     * @param int $id movieId
     * @return \Illuminate\Contracts\View\View|\Illuminate\Contracts\View\Factory
     */
    public function show($id)
    {
        $user = $this->getUser();
        $cartQuantity = $this->cartItemCount($user);

        $eventData = Event::with("movie", "room", "room.rows", "tickets", "tickets.reservation")->where("end_event", ">", Carbon::now())->findOrFail($id);

        $pricingRows = [];
        $prevPrice = null;

        $rowNames = ["A", "B", "C",];
        $i = 0;
        foreach ($eventData->room->rows as $row) {
            if (!$prevPrice) $prevPrice = $row->price;
            if ($prevPrice != $row->price) $i++;
            $pricingRows[$row->price] = ["name" => $rowNames[$i], "price" => $row->price];
            $prevPrice = $row->price;
        }

        $tickets = $this->sortTickets($eventData->tickets, $user);
        $total = $eventData->tickets->whereIn("status", config("constants.ticket_status_codes.selected"))->where($user->queryCondition, $user->id)->sum("price");

        return view("event.show", compact("eventData", "tickets", "total", "user", "cartQuantity", "pricingRows"));
    }

    /**
     * Sort tickets for event to adapt styling in view
     * @param mixed $tickets
     * @param mixed $user
     * @return array $sortedTickets
     */
    public function sortTickets($tickets, $user)
    {
        $sortedTickets = [];
        foreach ($tickets as $ticket) {
            if ($ticket["status"] == config("constants.ticket_status_codes.in_payment") || $ticket["status"] == config("constants.ticket_status_codes.sold_at_reception") || $ticket["status"] == config("constants.ticket_status_codes.in_support") || $ticket["status"] == config("constants.ticket_status_codes.bought_online")) {
                $sortedTickets[$ticket["seat"]]["sold"] = "sold";
            } else if ($ticket["status"] == config("constants.ticket_status_codes.selected")) {
                if ($user->type == "employee" && ($ticket["employee_id"] != NULL && $ticket["employee_id"] == $user->id)) {
                    $sortedTickets[$ticket["seat"]] = $ticket->id;
                } elseif ($user->type == "registeredUser" && $ticket["user_id"] != NULL && $ticket["user_id"] == $user->id) {
                    $sortedTickets[$ticket["seat"]] = $ticket->id;
                } elseif ($ticket["guest_id"] == $user->id) {
                    $sortedTickets[$ticket["seat"]] = $ticket->id;
                } else $sortedTickets[$ticket["seat"]]["sold"] = "sold";
            } else if ($ticket["status"] == config("constants.ticket_status_codes.reserved")) {
                if ($ticket->reservation->deleted_at && $user->type == "employee") {
                    $sortedTickets[$ticket["seat"]]["expired"] = $ticket->id;
                } else {
                    $sortedTickets[$ticket["seat"]]["sold"] = "sold";
                }
            }
        }

        return $sortedTickets;
    }
}

resources/views/event/show.blade.php
@extends('layouts.app')

@section('pageTitle','Saalansicht')

@section('content')

@push("scripts")
<script src="{{ asset('js/tickets/deleteSelectedSeat.js')}}"></script>
<script src="{{ asset('js/tickets/selectSeat.js')}}"></script>
<script src="{{ asset('js/tickets/reserve.js')}}"></script>
@endpush


@if(session("success"))
<div class="alert alert-success"> {{session("success")}}</div>
@elseif(session("error"))
<form action="{{route("ticket.destroyTicketsWithDifferentEvent")}}" method="POST">
   @csrf
   @method("DELETE")
   <input type="hidden" name="event_id" value="{{$eventData->id}}">
   <button class="btn btn-warning">{{session("error")}}</button>
</form>
@elseif(session("seatTaken"))
<div class="alert alert-warning"> {{session("seatTaken")}}</div>
@endif

<div class="event container-fluid">
   <h1 class="text-center my-4">{{$eventData->movie->title}}</h1>
   <h2 class="room text-center">{{$eventData->room->name}}</h2>
   <h3 class="room text-center">{{ \Carbon\Carbon::parse($eventData["start_event"])->format('H:i | d.m.Y')}}
   </h3>
   <div class="rows d-flex justify-content-center text-center">
      <div class="row-width overflow-auto">
         @php
         $prevMaxSeat = NULL;
         foreach ($eventData->room->rows as $row) :
         if ($row->row == 1){
         $seat = $row->row;
         $lastSeat = intval($row->last_seat_num);
         }
         else{
         $seat = $prevMaxSeat + 1;
         $lastSeat = intval($row->last_seat_num);
         }
         @endphp
         <div class="row">
            @if($row->row == 1 || $row->row == 2)<div class="text-center col-1  align-self-center"><strong>A</strong>
            </div>
            @elseif($row->row == 3 || $row->row == 4)<div class="text-center col-1  align-self-center">
               <strong>B</strong></div>
            @elseif($row->row == 5)<div class="text-center col-1  align-self-center"><strong>C</strong></div>
            @endif
            <div class="col-11 seats row flex-nowrap">
               @while ($seat <= $lastSeat) @if(isset($tickets[$seat]["sold"])) <div>
                  <button class="seat-height seat-width seat h3 m-0 sold bg-danger" data-row="{{$row->row}}"
                     data-seat="{{$seat}}">
                     &times;
                  </button>
            </div>
            @elseif(isset($tickets[$seat]) && is_int($tickets[$seat]))
            <form class="formDelete event row" action="{{route("ticket.destroy",$tickets[$seat])}}" method="POST">
               @csrf
               @method("delete")
               <input type="hidden" name="seat" value="{{$seat}}">
               <input type="hidden" name="row" value="{{$row->row}}">
               <input type="hidden" name="event_id" value="{{$eventData->id}}">
               <button
                  class="seat-height seat-width seat bg-warning selected">{{$seat < 10 ? "0".$seat : $seat}}</button>
            </form>
            @elseif(isset($tickets[$seat]["expired"]))
            <form class="formDelete event row" action="{{route("ticket.destroy",$tickets[$seat]["expired"])}}"
               method="POST">
               @csrf
               @method("delete")
               <input type="hidden" name="reservation_expired" value="reservation_expired">
               <input type="hidden" name="seat" value="{{$seat}}">
               <input type="hidden" name="row" value="{{$row->row}}">
               <input type="hidden" name="event_id" value="{{$eventData->id}}">
               <button
                  class="seat-height seat-width seat selected bg-primary">{{$seat < 10 ? "0".$seat : $seat}}</button>
            </form>
            @else
            <form class="formStore row event" action="{{route("ticket.store")}}" method="POST" class="seat">
               @csrf
               <input type="hidden" name="seat" value="{{$seat}}">
               <input type="hidden" name="row" value="{{$row->row}}">
               <input type="hidden" name="event_id" value="{{$eventData->id}}">
               <button class="seat-height seat-width">{{$seat < 10 ? "0".$seat : $seat}}</button>
            </form>
            @endif
            @php $seat++; @endphp
            @endwhile
         </div>
      </div>
      @php
      $prevMaxSeat = $row->last_seat_num;
      endforeach
      @endphp

      <div class="row py-4">
         <div class="col-1 "></div>
         <div class="text-left col col-sm-4 pl-0">
            @foreach($pricingRows as $pricingRow)
            <div class="row">
               <p class="col-8 col-sm-6"><strong>Rang {{$pricingRow["name"]}}</strong></p>
               <p><strong>{{$pricingRow["price"]}}€</strong></p>
            </div>
            @endforeach
         </div>
         <div class="d-none d-sm-block col-3"></div>
         <div class="col">
            <div class="d-flex">
               <p class="border-danger pl-3 status"><strong>Vergeben</strong></p>
            </div>
            <div class="d-flex">
               <p class="border-warning pl-3 status"><strong>Ausgewählt</strong></p>
            </div>
            @can("admin&employee")
            <div class="d-flex">
               <p class="border-primary pl-3 status"><strong>Verfallen</strong></p>
            </div>
            @endcan
         </div>
      </div>
   </div>

</div>


<div class="text-center border-top mb-4">
   <div class="my-4">
      <strong>Preis: <span id="total">{{$total}}</span>€</strong>
   </div>
   <a href="{{route("cart.index")}}" class="cart btn btn-success mb-2 @if(!$total)disabled @endif">Zur
      Bestellübersicht</a>
</div>


<div class="modal" data-toggle="modal" id="exampleModal" tabindex="-1" role="dialog">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title"></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <p></p>
         </div>
         <div class="modal-footer">
            <button id="removeOtherTickets" type="button" class="btn btn-primary"></button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Schließen</button>
         </div>
      </div>
   </div>
</div>

@endsection

<style>
   .seat-height {
      height: 54px;
   }

   .seat-width {
      width: 50px;
   }

   /* .row-width {
      width: 600px;
   } */

   .status {
      border-left: 5px solid;
   }

   .seats {
      cursor: pointer;
   }

   @media only screen and (max-width: 576px) {
      .row-width>.row:not(:last-child) {
         /* transform: scale(.5) */
      }
   }
</style>